// =============================================================================
// WIMC — MSG91 SMS delivery (plain transactional SMS, not MSG91's OTP-widget
// product — Supabase Auth already generates the OTP; this just delivers it).
//
// Used exclusively by the Supabase "Send SMS" Auth Hook
// (src/app/api/webhooks/send-sms/route.ts) to replace Twilio, which does not
// reliably deliver OTP SMS to Indian numbers.
//
// Required env vars:
//   MSG91_AUTH_KEY          — from MSG91 dashboard → API → Auth Key
//   MSG91_SENDER_ID         — DLT-approved 6-char sender ID
//   MSG91_OTP_TEMPLATE_ID   — DLT-approved Flow/template ID for the OTP SMS
//   MSG91_OTP_TEMPLATE_VAR  — the variable name used inside that template
//                             (whatever you named it when creating the DLT
//                             template in MSG91, e.g. "OTP" or "VAR1")
//
// Unlike src/lib/whatsapp.ts, this does NOT fail silently: the Send SMS hook
// contract requires a real error response when delivery fails so Supabase
// knows the OTP was never sent, so `sendOtpSms` throws on any failure.
// =============================================================================

import 'server-only'

const MSG91_FLOW_URL = 'https://api.msg91.com/api/v5/flow/'

/**
 * Sends a DLT-approved transactional SMS containing the given OTP to an
 * Indian mobile number via MSG91's Flow API.
 *
 * @param phone - E.164 phone number, e.g. `+919876543210`.
 * @param otp - The OTP code already generated by Supabase Auth.
 * @throws If required env vars are missing or MSG91 reports a failure.
 */
export async function sendOtpSms(phone: string, otp: string): Promise<void> {
  const authKey    = process.env.MSG91_AUTH_KEY
  const senderId   = process.env.MSG91_SENDER_ID
  const templateId = process.env.MSG91_OTP_TEMPLATE_ID
  const templateVar = process.env.MSG91_OTP_TEMPLATE_VAR

  if (!authKey || !senderId || !templateId || !templateVar) {
    throw new Error(
      'MSG91 is not configured — missing one of MSG91_AUTH_KEY, ' +
      'MSG91_SENDER_ID, MSG91_OTP_TEMPLATE_ID, MSG91_OTP_TEMPLATE_VAR',
    )
  }

  // MSG91 expects the mobile number without the leading '+'.
  const mobile = phone.replace(/^\+/, '')

  const response = await fetch(MSG91_FLOW_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      authkey: authKey,
    },
    body: JSON.stringify({
      template_id: templateId,
      sender: senderId,
      recipients: [
        {
          mobiles: mobile,
          [templateVar]: otp,
        },
      ],
    }),
  })

  const result = await response.json().catch(() => null)

  if (!response.ok || result?.type !== 'success') {
    throw new Error(
      `MSG91 send failed: ${response.status} ${JSON.stringify(result)}`,
    )
  }
}
